name = "WaveletCompression"
uuid = "231701f1-e831-4834-94ff-20f2ae2cd6de"
authors = ["Shalin Patel <shalin.kp.patel@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
